# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default
  demands:
    Unity_2020.3.0f1

steps:
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.AtrifactStagingDirectory)'
    Contents: '**/*'
- task: DeleteFiles@1
  inputs:
   SourceFolder: '$(Build.Repository.LocalPath)\Hadar\Library'
   Contents: '**/*'
- task: CmdLine@2
  inputs: 
   script: 'if EXIST "$(Build.BinariesDirectory)\Library\" move "$(Build.BinariesDirectory)\Library" "$(Build.Repository.LocalPath)\Hadar\Library"'
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'WebGL'
    unityProjectPath: 'Hadar'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'Hadar'
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\Library'
    Contents: '**/*'
- task: CmdLine@2
  inputs:
    script: 'move "$(Build.Repository.LocalPath)\Hadar\Library" "$(Build.BinariesDirectory)\Library"'