name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Hadar
        unityVersion:
          - 2020.3.0f1
        targetPlatform:
          - StandaloneWindows64
          - WebGL
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
        
    - name: Loading/Saving cached files
      uses: actions/cache@v2
      with:
        path: ${{ matrix.projectPath }}/Library
        key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
        restore-keys: |
          Library-${{ matrix.projectPath }}-
          Library-

    - name: Building project
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: ${{ matrix.projectPath }}
        unityVersion: ${{ matrix.unityVersion }}
        targetPlatform: ${{ matrix.targetPlatform }}
        
    - name: Uploading artefact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.projectPath }} - ${{ matrix.targetPlatform }}
